import PlaceholderImage from './PlaceholderImage';

type SiteImageProps = {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** LCP image — eager-load and request at high priority. */
  priority?: boolean;
  className?: string;
  rounded?: string;
  placeholderLabel?: string;
  /** Override the aspect ratio (e.g. "16 / 10"). */
  aspectRatio?: string;
  /**
   * `sizes` attribute for responsive variants. Tells the browser the
   * image's display width at each breakpoint so it picks the smallest
   * srcset candidate that fits. Example: "(min-width: 768px) 540px, 100vw".
   * Default: 100vw (assumes full-bleed).
   */
  sizes?: string;
  /**
   * Render the cream "Image coming soon" placeholder instead of the image.
   * Set true on call sites whose image hasn't been dropped into public/images/
   * yet. Drop the prop once the file exists.
   */
  placeholder?: boolean;
};

// AVIF sources have responsive variants generated by scripts/optimize-images.mjs:
// foo.avif → foo-400.avif, foo-800.avif (the original is the largest).
const RESPONSIVE_WIDTHS = [400, 800] as const;

function buildAvifSrcSet(src: string, originalWidth: number): string {
  const base = src.replace(/\.avif$/, '');
  const candidates = RESPONSIVE_WIDTHS
    .filter((w) => w < originalWidth)
    .map((w) => `${base}-${w}.avif ${w}w`);
  candidates.push(`${src} ${originalWidth}w`);
  return candidates.join(', ');
}

export default function SiteImage({
  src,
  alt,
  width,
  height,
  priority,
  className = '',
  rounded = 'rounded-2xl',
  placeholderLabel,
  aspectRatio,
  sizes = '100vw',
  placeholder,
}: SiteImageProps) {
  if (placeholder) {
    return (
      <PlaceholderImage
        width={width}
        height={height}
        label={placeholderLabel ?? `Image coming soon: ${alt}`}
        className={className}
        rounded={rounded}
        aspectRatio={aspectRatio}
      />
    );
  }

  const isAvif = src.endsWith('.avif');
  const style = aspectRatio ? { aspectRatio } : undefined;
  const imgClass = `${rounded} ${className}`.trim();

  if (isAvif) {
    return (
      <picture>
        <source
          type="image/avif"
          srcSet={buildAvifSrcSet(src, width)}
          sizes={sizes}
        />
        <img
          src={src}
          alt={alt}
          width={width}
          height={height}
          loading={priority ? 'eager' : 'lazy'}
          fetchPriority={priority ? 'high' : 'auto'}
          decoding="async"
          className={imgClass}
          style={style}
        />
      </picture>
    );
  }

  return (
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : 'auto'}
      decoding="async"
      className={imgClass}
      style={style}
    />
  );
}
